import java_cup.runtime.*;
import java.io.*;
import java.util.*;

parser code 
{:

  public static void main(String[] args) throws Exception 
  {
    XmlToJson xmlToJson = new XmlToJson(new FileReader(args[0]));
    parser p = new parser(xmlToJson);
    Object result = p.parse().value;

    p.createCodeJson();
  }

  StringBuilder stringJson = new StringBuilder();

  public void createCodeJson() throws Exception
  {
      try(PrintWriter out = new PrintWriter("output.txt"))
      {
          out.println("COIso rodanddo");
      }
  }

:};


terminal OPEN_ANGLE, CLOSE_ANGLE, SLASH, ASSIGN, LESS_THAN, GREATER_THAN, 
         AMPERSAND, APOSTROPHE, QUOTE_MARK, SPACE;

terminal String LITERAL_STRING, TEXT;
terminal Integer NUMBER;

non terminal xml, element, elementList, openElement, closeElement, selfCloseElement, 
                   id, text;

xml ::= elementList;

element ::= openElement text closeElement      | 
            openElement closeElement           |
            openElement element closeElement   |
			      selfCloseElement                   ;

elementList ::= elementList element   |
                element               ;
              
openElement ::= OPEN_ANGLE id CLOSE_ANGLE | 
				        OPEN_ANGLE id SPACE id ASSIGN LITERAL_STRING CLOSE_ANGLE;
				
closeElement ::= OPEN_ANGLE SLASH id CLOSE_ANGLE;

selfCloseElement ::= OPEN_ANGLE id SLASH CLOSE_ANGLE;

id ::= TEXT;
text ::= TEXT;