import java_cup.runtime.*;
import java.io.*;
import java.util.*;

parser code 
{:

  public static void main(String[] args) throws Exception 
  {
    XmlToJson xmlToJson = new XmlToJson(new FileReader(args[0]));
    parser p = new parser(xmlToJson);
    Object result = p.parse().value;

    p.createCodeJson();
  }

  StringBuilder stringJson = new StringBuilder();

  public void createCodeJson() throws Exception
  {
      try(PrintWriter out = new PrintWriter("output.txt"))
      {
          out.println("COIso rodanddo");
      }
  }

:};


terminal OPEN_ANGLE, CLOSE_ANGLE, SLASH, ASSIGN, QUOTE_STRING, LESS_THAN, GREATER_THAN, 
         AMPERSAND, APOSTROPHE, QUOTE_MARK;

terminal String ID, LITERAL_STRING, TEXT;
terminal Integer NUMBER;

non terminal xml_, element, elementList, openElement, closeElement, selfCloseElement;

xml_ ::= elementList;

element ::= openElement TEXT closeElement      | 
            openElement closeElement           |
            openElement element closeElement   |
			      selfCloseElement                   ;

elementList ::= elementList element   |
                element               ;
              
openElement ::= OPEN_ANGLE ID CLOSE_ANGLE | 
				        OPEN_ANGLE ID ID ASSIGN LITERAL_STRING CLOSE_ANGLE;
				
closeElement ::= OPEN_ANGLE SLASH ID CLOSE_ANGLE;

selfCloseElement ::= OPEN_ANGLE ID SLASH CLOSE_ANGLE;